import { Together } from "together-ai";
import { marked } from 'marked';
import hljs from 'highlight.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import dotenv from 'dotenv';
import { renderHtmlToPdf } from '../utils/pdfRenderer.js';
import { normalizeMathMarkdown } from '../utils/documentQuality.js';
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Constants
const HISTORY_FILE = 'history.json';
const SECTION_PREFIX = 'section';
const COMBINED_FILE = 'combined-sections.txt';

// AI Client
let together = null;
function ensureTogether() {
  if (together) return together;
  const apiKey = process.env.TOGETHER_API_KEY;
  if (!apiKey) {
    throw new Error('TOGETHER_API_KEY is not set in environment.');
  }
  together = new Together({ apiKey });
  return together;
}

// Markdown setup
marked.setOptions({
  highlight: (code, lang) => {
    const validLang = hljs.getLanguage(lang) ? lang : 'plaintext';
    return hljs.highlight(code, { language: validLang }).value;
  }
});

// === Helpers ===
function saveToFile(filename, content) {
  fs.writeFileSync(filename, content);
  console.log(`✔ Saved: ${filename}`);
}

function deleteFile(filePath) {
  try {
    fs.unlinkSync(filePath);
    console.log(`🗑 Deleted: ${filePath}`);
  } catch (err) {
    console.error(`❌ Error deleting ${filePath}:`, err);
  }
}

function combineChapters(files) {
  let combined = '';
  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    combined += content + '\n\n';
  }
  fs.writeFileSync(COMBINED_FILE, combined.trim());
  return combined;
}

function formatMath(content) {
  return normalizeMathMarkdown(content);
}

function cleanUpAIText(text) {
  const noDividers = text.replace(/[-=_*~]{5,}/g, '');
  return noDividers
    .replace(/\n{3,}/g, '\n\n')
    .replace(/\n\s*$/g, '')
    .replace(/[\u2013\u2014]/g, '-')
    .trim();
}

// === PDF Generator ===
export async function generatePDF(content, outputPath) {
  const cleaned = cleanUpAIText(formatMath(String(content)));
  const html = `
  <html>
    <head>
      <meta charset="utf-8">
      <title>Research Paper</title>
      <script>
        window.MathJax = {
          tex: { inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']] },
          svg: { fontCache: 'global' }
        };
      </script>
      <script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/prism.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-javascript.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-python.min.js"></script>
      <link href="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/themes/prism.min.css" rel="stylesheet">
      <style>
        @page { margin: 80px 60px; size: A4; }
        body { font-family: Georgia, 'Times New Roman', serif; font-size: 14px; line-height: 1.7; color: #222; margin: 0; padding: 0; text-align: justify; }
        h1, h2, h3 { margin-top: 2em; margin-bottom: 0.7em; color: #1f2937; }
        h1 { font-size: 26px; border-bottom: 2px solid #d1d5db; padding-bottom: 8px; page-break-before: always; }
        h2 { font-size: 21px; }
        h3 { font-size: 17px; }
        p { margin: 0 0 1em 0; }
        pre { background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e5e7eb; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word; }
        code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }
        pre code { background: transparent; padding: 0; }
        table { border-collapse: collapse; width: 100%; margin: 1.5em 0; page-break-inside: avoid; }
        th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
        th { background: #f3f4f6; }
        blockquote { border-left: 4px solid #64748b; margin: 1.5em 0; padding: 0.8em 1.2em; background: #f8fafc; }
      </style>
    </head>
    <body>
      ${marked.parse(cleaned)}
    </body>
  </html>`;

  await renderHtmlToPdf(html, outputPath, {
    margin: { top: '80px', bottom: '80px', left: '60px', right: '60px' },
    headerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;">Generated by Bookgen.ai</div>',
    footerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>'
  });
}

// === Main Function ===
export async function generateResearchPaperS(topic, userId) {
  try {
    console.log(`📄 Generating SHORT research paper for user: ${userId} with topic: ${topic}`);

    let conversationHistory = [{
      role: "system",
      content: "You are Hailu, a professional researcher. Write a short but structured research paper. Include introduction, methodology, analysis, and conclusion."
    }];

    async function askAI(prompt) {
      const messages = [...conversationHistory, { role: 'user', content: prompt }];
      const response = await ensureTogether().chat.completions.create({
        messages,
        model: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free",
        max_tokens: 3000,
        temperature: 0.8,
      });

      let reply = response.choices[0].message.content || '';
      reply = reply.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
      conversationHistory.push({ role: 'user', content: prompt });
      conversationHistory.push({ role: 'assistant', content: reply });
      return reply;
    }

    async function generateSection(prompt, sectionNum) {
      const sectionText = await askAI(prompt);
      const filename = `research-section-${userId}-${sectionNum}.txt`;
      saveToFile(filename, sectionText);
      return filename;
    }

    const prompts = [
      { text: `# Abstract\n\nWrite a 200-word abstract for a research paper on "${topic}". Give it a proper title.`, name: 'abstract' },
      { text: `# Introduction\n\nWrite a 600-word introduction on "${topic}". Include background, objectives, and importance.`, name: 'introduction' },
      { text: `# Methodology\n\nDescribe methodology with subheadings like "## Data Collection" and "## Analysis".`, name: 'methodology' },
      { text: `# Findings\n\nPresent findings with examples and markdown formatting.`, name: 'findings' },
      { text: `# Discussion\n\nDiscuss the implications and limitations of the findings.`, name: 'discussion' },
      { text: `# Conclusion\n\nSummarize the findings and give recommendations.`, name: 'conclusion' },
      { text: `# References\n\nGenerate 5-10 APA style references in markdown.`, name: 'references' },
    ];

    const sectionFiles = [];
    for (let i = 0; i < prompts.length; i++) {
      console.log(`📘 Generating section ${i + 1}: ${prompts[i].name}`);
      const file = await generateSection(prompts[i].text, i + 1);
      sectionFiles.push(file);
    }

    const combinedContent = combineChapters(sectionFiles);
    const safeTopic = topic.slice(0, 20).replace(/\s+/g, "_");
    const fileName = `research_${userId}_${safeTopic}.pdf`;
    const outputDir = path.join(__dirname, '../pdfs');
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);

    const outputPath = path.join(outputDir, fileName);
    await generatePDF(combinedContent, outputPath);

    sectionFiles.forEach(deleteFile);

    console.log(`✅ Research paper generated: ${outputPath}`);
    return outputPath;

  } catch (error) {
    console.error('❌ Short research paper generation failed:', error);
    throw error;
  }
}
