import fs from 'fs';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

const DEFAULT_PDF_OPTIONS = {
  format: 'A4',
  printBackground: true,
  preferCSSPageSize: true,
  margin: {
    top: '90px',
    bottom: '80px',
    left: '70px',
    right: '70px'
  },
  displayHeaderFooter: true,
  headerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;">Generated by bookgen.ai</div>',
  footerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;"><span class="pageNumber"></span></div>',
  timeout: 120000
};

function cleanAssetUrlAttributes(html) {
  return html.replace(/\b(src|href)=(['"])(https?:\/\/[^'"]*?)\s+\2/g, (_, attr, quote, url) => {
    return `${attr}=${quote}${url.trim()}${quote}`;
  });
}

async function getExecutablePath() {
  if (process.env.CHROME_EXECUTABLE_PATH) {
    return process.env.CHROME_EXECUTABLE_PATH;
  }

  return chromium.executablePath();
}

function buildLaunchArgs() {
  return [
    ...chromium.args,
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--disable-gpu',
    '--font-render-hinting=medium'
  ];
}

async function waitForClientSideRendering(page) {
  await page.evaluate(async () => {
    if (document.fonts?.ready) {
      await document.fonts.ready;
    }
  });

  await page.waitForFunction(() => !window.MathJax || window.MathJax.startup?.document?.state?.() >= 200 || Boolean(window.MathJax.typesetPromise), {
    timeout: 30000
  }).catch(() => {});

  await page.evaluate(async () => {
    if (window.MathJax?.typesetPromise) {
      await window.MathJax.typesetPromise();
    }

    if (window.Prism?.highlightAll) {
      window.Prism.highlightAll();
    }
  });
}

export async function renderHtmlToPdf(html, outputPath, options = {}) {
  const browser = await puppeteer.launch({
    args: buildLaunchArgs(),
    defaultViewport: { width: 1240, height: 1754, deviceScaleFactor: 1 },
    executablePath: await getExecutablePath(),
    headless: chromium.headless
  });

  try {
    const page = await browser.newPage();
    page.setDefaultNavigationTimeout(120000);
    page.setDefaultTimeout(120000);
    await page.emulateMediaType('print');

    await page.setContent(cleanAssetUrlAttributes(html), {
      waitUntil: ['load', 'domcontentloaded', 'networkidle0'],
      timeout: 120000
    });

    await waitForClientSideRendering(page);

    await page.pdf({
      ...DEFAULT_PDF_OPTIONS,
      ...options,
      margin: {
        ...DEFAULT_PDF_OPTIONS.margin,
        ...options.margin
      },
      path: outputPath
    });

    if (!fs.existsSync(outputPath) || fs.statSync(outputPath).size < 1024) {
      throw new Error('PDF renderer produced an empty or invalid file.');
    }

    return outputPath;
  } finally {
    await browser.close();
  }
}
