import fs from 'fs';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

const DEFAULT_PDF_OPTIONS = {
  format: 'A4',
  printBackground: true,
  preferCSSPageSize: true,
  margin: {
    top: '90px',
    bottom: '80px',
    left: '70px',
    right: '70px'
  },
  displayHeaderFooter: true,
  headerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;">Generated by bookgen.ai</div>',
  footerTemplate: '<div style="font-size:10px;text-align:center;width:100%;color:#6b7280;"><span class="pageNumber"></span></div>'
};

async function getExecutablePath() {
  if (process.env.CHROME_EXECUTABLE_PATH) {
    return process.env.CHROME_EXECUTABLE_PATH;
  }

  return chromium.executablePath();
}

function buildLaunchArgs() {
  return [
    ...chromium.args,
    '--no-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--font-render-hinting=none'
  ];
}

export async function renderHtmlToPdf(html, outputPath, options = {}) {
  const browser = await puppeteer.launch({
    args: buildLaunchArgs(),
    defaultViewport: chromium.defaultViewport,
    executablePath: await getExecutablePath(),
    headless: chromium.headless
  });

  try {
    const page = await browser.newPage();
    page.setDefaultNavigationTimeout(120000);
    page.setDefaultTimeout(120000);

    await page.setContent(html, { waitUntil: ['load', 'domcontentloaded', 'networkidle0'] });

    await page.evaluate(async () => {
      if (document.fonts?.ready) {
        await document.fonts.ready;
      }

      if (window.MathJax?.typesetPromise) {
        await window.MathJax.typesetPromise();
      }

      if (window.Prism?.highlightAll) {
        window.Prism.highlightAll();
      }
    });

    await page.pdf({
      ...DEFAULT_PDF_OPTIONS,
      ...options,
      margin: {
        ...DEFAULT_PDF_OPTIONS.margin,
        ...options.margin
      },
      path: outputPath
    });

    if (!fs.existsSync(outputPath) || fs.statSync(outputPath).size === 0) {
      throw new Error('PDF renderer produced an empty file.');
    }

    return outputPath;
  } finally {
    await browser.close();
  }
}
